NAME: DeepFashion_s1

SAVE_DIR: runs
DATA:
  NUM_TRIPLETS: 100000
  TRAIN_BATCHSIZE: 64
  TEST_BATCHSIZE: 128
MODEL:
  TRANSFORMER:
    ENABLE: False
  SINGLE:
    ENABLE: True
  MEMORYBANK:
    PROTO_BANK_SIZE: 1000

SOLVER:
  DECAY_RATE: 0.9
  STEP_SIZE: 3
  EPOCHS: 100
  BASE_LR: 1e-4
  REGION_WEIGHT: 1.
  LOG_PERIOD: 500

INPUT:
  THRESHOLD: 0.1