NAME: FashionAI_s2

SAVE_DIR: runs
DATA:
  NUM_TRIPLETS: 100000
  TRAIN_BATCHSIZE: 16
  TEST_BATCHSIZE: 64

MODEL:
  TRANSFORMER:
    ENABLE: True
  SINGLE:
    ENABLE: False
  
SOLVER:
  DECAY_RATE: 0.9
  STEP_SIZE: 2
  EPOCHS: 200
  REGION_WEIGHT: 1.
  INTER_WEIGHT: 0.04 # 0.04
  PATCH_WEIGHT: 0.1 # 0.1
  BASE_LR: 5.5e-5
  BASE_LR_SLOW: 1e-5
  BETA : 0.3
  ALPHA: 12.
  LOG_PERIOD: 800

INPUT:
  THRESHOLD: 0.1